{"name": "Логин с неверным логином", "status": "passed", "start": 1723673937467, "stop": 1723673937583, "uuid": "b77eae9a-c59b-4998-a670-1fd802151dac", "historyId": "be4af5dd2d0912060fc82553dcc9f2f5", "testCaseId": "be4af5dd2d0912060fc82553dcc9f2f5", "fullName": "tests.test_login_user.test_login_user_negative.TestLoginUserNegative#test_login_user_with_invalid_email", "labels": [{"name": "parentSuite", "value": "tests.test_login_user"}, {"name": "suite", "value": "test_login_user_negative"}, {"name": "subSuite", "value": "TestLoginUserNegative"}, {"name": "host", "value": "DESKTOP-0TG4V14"}, {"name": "thread", "value": "14620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user.test_login_user_negative"}]}